### ISSUE TITLE
Glitch links don't work anymore

### ISSUE THREAD

**Issue by carlinmack** [strawstack/HugoGlitch#1]
As noted, the links lead to 404 now

**Comment by strawstack** [comment]
Thanks for noting this. Since making this repo, I’ve found that a better way to host a Hugo blog is directly in GitHub, and then using a site like Netlify to rebuild the site automatically when the GitHub repo changes. One can add and edit articles directly on GitHub, and this GitHub/Netlify solution is still free as well. 

Hopefully that info is useful to you. I may delete this repo in the near future. It should also be possible to host using GitHub actions instead of Netlify if one wants, but I’ve found Netlifys interface to be more intuitive.

**Comment by carlinmack** [comment]
I think it would be better to add this to the readme and archive the repo :) it's useful to know that it is possible to use Hugo with glitch as I think glitch is marginally nicer for someone who doesn't want to get involved with version control (which is why I was checking out your repo).

**Comment by strawstack** [comment]
Ok, thanks for the info. I’ll probably make your suggested changes soon.

**Comment by strawstack** [comment]
I added to the readme, and I'll now archive the repo
